### ISSUE TITLE
Add an iD editor button

### ISSUE THREAD

**Issue by ignaciolep** [hauke96/simple-task-manager#105]
Hi,

Please consider adding iD integration. At least an "Edit" button to open the https://www.openstreetmap.org/edit url with the coodinates and zoom of the task.

We recently tried to use this project to map a fires zone (https://stm.hauke-stieler.de/project/109) but seeing that JOSM is the only editor, we were forced to use another (old) tasking manager.

The iD editor is right tool to allow new editors to participate as it's really simple to use, you just need a browser, and it even works on tablets. In this case, people that never contributed to OSM wanted to do it, as this mapping project a way to help their local firemen's work.

Thanks!

**Comment by hauke96** [comment]
There was the PR #88 and the issue #87 for exactly this. So this button will be part of the next release 1.1.0.
