### ISSUE TITLE
Zoom in/out options

### ISSUE THREAD

**Issue by ScriptForAll** [hauke96/simple-task-manager#125]
Is there a point of having these options since the base map has them already?

**Comment by hauke96** [comment]
Yeah I consider this as a bug, we don't need two button next to each other to zoom in and out :D

**Comment by hauke96** [comment]
Removed the extra buttons and did some layout changes:

![Screenshot_20201219_003748](https://user-images.githubusercontent.com/9700906/102672919-7f32d300-4192-11eb-8599-8e9baa703c58.png)
