### ISSUE TITLE
Feature: Support project template

### ISSUE THREAD

**Issue by miurahr** [hauke96/simple-task-manager#137]
It may be great when STM support a project template.

- User can mark as the template when creating new project.
- The template project cannot be used as normal project.
- When creating new project, admin can select template.

related to #68

**Comment by miurahr** [comment]
It may be enough that simple a geojson file with name field.
When supporting a feature to export a project as geojson, user can import it as an initial task definition.

**Comment by hauke96** [comment]
I wouldn't implement your first idea (marking a project as template and so on) but your second idea (using an exported project as template) sound good. I can also imagine to also implement an additional way: A copy-Button to directly copy a project without exporting and importing it.
