### ISSUE TITLE
Bug: Typing Name or Description does not work

### ISSUE THREAD

**Issue by westnordost** [hauke96/simple-task-manager#154]
If a type a "d" in the name or description for a project, it does not work. Instead it triggers some button in the map view.

**Comment by hauke96** [comment]
Thanks for reporting this. The latest release contains shortcuts (not yet documented in the wiki-page, I'll add this soon) which are a bit to ... motivated :smile: so they also trigger when an input field is currently focused.

I'm currently testing this on my test instance, so the bug fix will go live today.

**Comment by hauke96** [comment]
Done, just deployed it on [stm.hauke-stieler.de](stm.hauke-stieler.de/).
