### ISSUE TITLE
Feature request: Edit project description

### ISSUE THREAD

**Issue by westnordost** [hauke96/simple-task-manager#156]
I noticed that a link is wrong after entering the description. Now I don't seem to be able to amend it

**Comment by hauke96** [comment]
What do you mean by "a link is wrong" and "amend it"? Can you describe the steps you did so that I can reproduce the behavior?

**Comment by westnordost** [comment]
I wrote the description, then created the project. Now I would like to change the description.

**Comment by hauke96** [comment]
When you open a project you can change the title and description in the "Settings"-tab:

![image](https://user-images.githubusercontent.com/9700906/124367639-57501c00-dc59-11eb-836e-dc20df38d2a9.png)

I think that's what you want?

**Comment by westnordost** [comment]
Oh! I was expecting that I could edit it in-place. Nevermind!
