### ISSUE TITLE
More descriptive task shape layer name (JOSM)

### ISSUE THREAD

**Issue by InsertUser** [hauke96/simple-task-manager#162]
When I use the "Open in JOSM" button to load a task in JOSM I get two layers, one for the task shape and one for the rest of the data. The data layer uses JOSM's default naming convention, while the task shape layer gets the name "task-shape". I don't know whether this is universal or only when JOSM is set to download remote control actions in a new layer. 

I think it would be useful if the task-shape layer quoted the individual task number as I have had a couple of occasions where I have had to reload the browser page while in the middle of a task and this often results in another (previous) task being shown on screen. 

If using two layers is independent of settings it might also be nice if the task shape layer was flagged with `upload=false`  to stop JOSM from complaining about un-uploaded data when deleting layers for completed tasks.

**Comment by InsertUser** [comment]
My incredibly naïve searching indicates that this might relate to task.service.ts lines [113](https://github.com/hauke96/simple-task-manager/blob/3bfb8325b24e20e44b0e0e342ee15e33c231168c/client/src/app/task/task.service.ts#L113) and [216](https://github.com/hauke96/simple-task-manager/blob/3bfb8325b24e20e44b0e0e342ee15e33c231168c/client/src/app/task/task.service.ts#L216)? But I have no idea how to test this.

**Comment by hauke96** [comment]
Hi, thanks for this feature request, all of this sounds quite useful. You're right, the line 113 is the interesting one and should be something like this:

```javascript
'http://localhost:8111/load_data?new_layer=true&layer_name=task ' + task.name + '&upload_policy=never&data=' + encodeURIComponent(this.getGeometryAsOsm(task)),
```

I'll change this withing the next release.

**Comment by hauke96** [comment]
Just implemented this. As I mentioned above, this will be part of the next release.
