### ISSUE TITLE
Feature: public project

### ISSUE THREAD

**Issue by JackNUMBER** [hauke96/simple-task-manager#172]
Share project without email invitation could be a good game changer for the tool. Only give the project's URL to a community and everyone can contribute.

It can be a status like "private" (default) or "public" in the project settings. With password in an other step?

More user participating = more contributors = more help for the project :)

**Comment by hauke96** [comment]
Hi, thanks for your feature suggestion :)

The topic of global/public projects already came up (e.g. in issue #49 and #102). However this topic is a bit ... delicate and I haven't found a satisfying solution yet. Read along the referenced issues if you're interested.

I'll close this one as it's a duplicate of the mentioned issues.
