### ISSUE TITLE
Subdivide shall preview the number of tasks

### ISSUE THREAD

**Issue by Strubbl** [hauke96/simple-task-manager#176]
It would be nice to see the resulting number of tasks, which i get from dividing. I mean, i can see the map and its squares, but having the number of squares would be nice in order to reduce the m² but stay within the 1000 tasks limit.

**Comment by hauke96** [comment]
Thank for this idea. I think the best place to display the number of sub-polygons would be after clicking the "preview" button, right? Showing the number after clicking the "divide" button wouldn't make much sense as you can see the number of tasks at the top of the task list.

This sounds like a nice and small feature to implement. I added this to the [1.4.3 project](https://github.com/hauke96/simple-task-manager/projects/15).

**Comment by Strubbl** [comment]
Yes, after clicking the "preview" button makes sense. But i cannot see "the number of tasks at the top of the task list". If i create a project, draw a polygon, go to tasks, use the task and click preview, i see only 1/1000.

**Comment by hauke96** [comment]
I implemented this in a quite simple manner:

![image](https://user-images.githubusercontent.com/9700906/175427397-e55ff91b-af34-4bd0-be3a-0d9bb724fd95.png)

This will be part of the next release.
