### ISSUE TITLE
ENV in Docker STM server 

### ISSUE THREAD

**Issue by fatuuse** [hauke96/simple-task-manager#179]
STM server do not listen on STM_DB_HOST env from Dockerfile. Hard-coded to localhost.

**Comment by fatuuse** [comment]
https://github.com/hauke96/simple-task-manager/blob/4bf07386c6171d509ec6e1bbd0312be6e556cd9d/server/database/init-db.sh#L9
should be ${STM_DB_HOST} not localhost?

**Comment by hauke96** [comment]
Hi, thanks for bringing this up. It depends on where the script runs but yeah, it should probably be `$STM_DB_HOST`. I'll look into that and will adjust it on the `dev` branch if needed.

**Comment by fatuuse** [comment]
I'm will set it up with docker containers not running with bridged net on a system with an postgres db already running on host system.

**Comment by hauke96** [comment]
I added the `STM_DB_HOST` variable to all scripts. With the next release (of v1.4.4), you should be able to fully configure the DB host. Please let my know if you encounter any problems or if I missed any spot.

Also take a look at the release-page of v1.4.4, some other things changed in that version as well and you might need to adjust your configs.

**Comment by hauke96** [comment]
Is now deployed and images are available via docker-hub. Note that I chose to set the version to 1.5.0 instead of 1.4.4.
