### ISSUE TITLE
Problem inviting user

### ISSUE THREAD

**Issue by loffa** [hauke96/simple-task-manager#188]
Hello,

I tried to invite a user today and discovered what I think is a bug.

It seems like API-request to get the user uid fails when using Chrome. It seems like the code automatically adds the Header for `Accepts: application/json`. This actually causes the response to become JSON, which  the code does not expect. In fact it is commented in the code for fetching a user that it should never return JSON. As the code expect XML this confuses the parser and it is not able to find the user object.

https://github.com/hauke96/simple-task-manager/blob/6576468c53fc7a0e753d28837c9ba86e98c8862e/client/src/app/user/user.service.ts#L44+1

Returns JSON:
```
curl https://api.openstreetmap.org/api/0.6/changesets?display_name=loffa -H "Accept: application/json"
```

Returns XML:
```
curl https://api.openstreetmap.org/api/0.6/changesets?display_name=loffa -H "Accept: application/xml"
```

### Possible solution

Either add the Accept heder for XML to always fetch that or convert the parser to JSON instead and get the name from that.

**Comment by hauke96** [comment]
Thanks for reporting the bug! The osm.org API finally supports JSON since last year.

I deployed a fix on the test instance https://stm-test.hauke-stieler.de. This also includes a lot of dependency updates, so please have a look and let me know if you notice anything.

**Comment by hauke96** [comment]
As I mentioned, this will be part of the next release of v1.4.4. I therefore close this issue.

**Comment by hauke96** [comment]
Is now deployed and images are available via docker-hub. Note that I chose to set the version to 1.5.0 instead of 1.4.4.
