### ISSUE TITLE
Task creation from import fails when boundary is a multipolygon

### ISSUE THREAD

**Issue by elevenchars** [hauke96/simple-task-manager#191]
When I try to import a geojson file from https://osm-boundaries.com/, switching to the "Tasks" tab gives the following error:

```Unexcpected error occured: Error: First and last Position are not equivalent.```

I have attached the multipolygon in question.

[OSMB-9f1b93c35b2ffb71201f11be3f3342ee4520c905.geojson.gz](https://github.com/hauke96/simple-task-manager/files/11866964/OSMB-9f1b93c35b2ffb71201f11be3f3342ee4520c905.geojson.gz)

**Comment by hauke96** [comment]
Added a fix for this problem. Feel free to check your usecase on https://stm-test.hauke-stieler.de (an account on the OSM dev environment master.apis.dev.openstreetmap.org is needed) and let me know if you experience any problems.
