### ISSUE TITLE
Migrate from OAuth 1.0a to OAuth2

### ISSUE THREAD

**Issue by stefanb** [hauke96/simple-task-manager#192]
OpenStreetmap is deprecating OAuth 1.0a.

See:
* https://github.com/openstreetmap/operations/issues/867
* https://www.openstreetmap.org/user/pnorman/diary/401157
* Spec: https://wiki.openstreetmap.org/wiki/OAuth#OAuth_2.0
* OAuth 2.0 Authorization Server Metadata: https://www.openstreetmap.org/.well-known/oauth-authorization-server
* Possible Go library: `golang.org/x/oauth2` with repository at https://github.com/golang/oauth2
  * Adding OSM endpoints: https://github.com/golang/oauth2/pull/631

**Comment by hauke96** [comment]
Thanks for the issue and links! I know about the deprecation but unfortunately my time is very limited. If anyone else want to work on this, feel free to let me know ;)

**Comment by hauke96** [comment]
I found some time working on this. OAuth2 will be used with v1.4.4 of STM. Thanks again for bringing this up and also thanks for the links, that saved me some time ;)

**Comment by stefanb** [comment]
Great! 🎉 🚀 
I guess this is still pending a release. Presumably in v1.4.4?

**Comment by hauke96** [comment]
Exactly, this will be deployed with version 1.4.4 (probably within the next few weeks).

**Comment by hauke96** [comment]
Is now deployed and images are available via docker-hub. Note that I chose to set the version to 1.5.0 instead of 1.4.4.
