### ISSUE TITLE
An OSM user invites me to their project, but the email about the invitation doesn't appear in my inbox

### ISSUE THREAD

**Issue by attilakundev** [hauke96/simple-task-manager#196]
As I saw, now I can add users in my project, however they don't get my invitation in their inbox and vice versa, I don't get their invite into their project. Could you look what causes this?

**Comment by hauke96** [comment]
Hi, the answer why no messages are sent is simple: It's not possible. First of all, STM doesn't mention/offer this functionality in the first place, so it's not a bug or something :wink: And second, the OSM API doesn't provide any functionality to send messages to users. The discussion page of the next API version ([API v0.7](https://wiki.openstreetmap.org/wiki/API_v0.7)) addresses this but currently it's simply not possible to implement such a notification feature :shrug:

**Comment by attilakundev** [comment]
Alright, I see. But if I added a user in my project, then why don't they see my project? Or how to do that they can see it (and vice versa)? Because it's unclear for me.

**Comment by hauke96** [comment]
Hmm, the whole invitation functionality works as expected on my machine. But I saw wrong database entries and created the bug ticket #197. Thanks for letting be know, I'm on it.

Btw.: I fixed the wrong database entries, so you should now see each others projects. Please do not use the invitation feature until I deployed a fix, thanks :wink:
