### ISSUE TITLE
User invitation not working properly

### ISSUE THREAD

**Issue by hauke96** [hauke96/simple-task-manager#197]
_(Unfortunately it works on my machine ...)_

When inviting users, the user _name_ and not the user _id_ is saved to `project.users` in the database.
See also #196 .

### Actions:

1. Add a check to the backend that the given UID actually looks like a uid
2. Check for frontend to determine correct UIDs for users
3. If easily possible: Move the whole "find UID by name"-thing to the backend

**Comment by attilakundev** [comment]
![image](https://github.com/hauke96/simple-task-manager/assets/35130944/eec855c3-034b-4f64-b4fd-2b1f61472342)
There's also this little problem I noticed. Now I can see the project of other mapper, however, in their project I can't open the tasks with JOSM. Only with iD editor. But I can open my tasks in JOSM which should be expected.

**Comment by hauke96** [comment]
> ![image](https://user-images.githubusercontent.com/35130944/282568216-eec855c3-034b-4f64-b4fd-2b1f61472342.png) There's also this little problem I noticed. Now I can see the project of other mapper, however, in their project I can't open the tasks with JOSM. Only with iD editor. But I can open my tasks in JOSM which should be expected.

Have you enabled the remote control feature in JOSM (preferences → remote control → enable remote control)? This is a thing that doesn't come out of the box.

**Comment by hauke96** [comment]
Ah, sorry, misread your comment. But still works for me in Firefox and Chrome when I use different accounts, also with accounts invited to a project and not being owner.

Do you have any console logs from the browser or any error messages of failed requests from your browsers network tab?

**Comment by attilakundev** [comment]
Nope, I unfortunately. Or only these:
```
Cache miss for user '8291281'
Cache miss for user '3087157'
```
