### ISSUE TITLE
Opening JOSM doesn't work properly

### ISSUE THREAD

**Issue by hauke96** [hauke96/simple-task-manager#198]
_(Unfortunately it works on my machine)_

Some users can't open JOSM from a task. See e.g. #197. This is the issue for further discussion and analysis.

**Comment by attilakundev** [comment]
![image](https://github.com/hauke96/simple-task-manager/assets/35130944/499154f0-af03-44f7-affb-cc1d3ba1b285)

This problem occurs when I try to open a task in project e.g. [491](https://stm.hauke-stieler.de/project/491), owned by OptikalCrow, but me, ottwiz on OSM, can't open the tasks in JOSM, just only from iD editor. I have remote control enabled and in my private projects such as: [494](https://stm.hauke-stieler.de/project/494), I can reach the tasks perfectly.  
![image](https://github.com/hauke96/simple-task-manager/assets/35130944/70e1e3b2-0337-442d-adc8-dfc7fc9458e2)

I posed the question to OptikalCrow on Discord so they can try if they can reproduce it.

**Comment by hauke96** [comment]
Any news on this?

Does it work when you manually call the URL to open something in JOSM. Like http://localhost:8111/load_and_zoom?new_layer=true&left=10.00520&right=10.00823&top=53.55413&bottom=53.55190 ?

**Comment by attilakundev** [comment]
![grafik](https://github.com/hauke96/simple-task-manager/assets/35130944/3c1f55cb-6659-449a-a0e6-0492ed5c43fe)

**Comment by attilakundev** [comment]
Not yet actually so I have JOSM running, but it seems not works when I try to take someone else's task. Unfortunately OptikalCrow didn't have time to try this out, he's busy with work. I might ask though someone from the OSM community if they can reproduce the same issue.

**Comment by attilakundev** [comment]
For my own project, I can open the task so it's got no problem at all. The link you provided (since I got JOSM running, I got OK as a response.
![grafik](https://github.com/hauke96/simple-task-manager/assets/35130944/6e591b62-7587-439e-89c3-1a594c9a8e51)

**Comment by hauke96** [comment]
Thanks for the response. Ok, so JOSM is genereally working, that's good. I'll have another look into this, but I can't promise anything.

**Comment by hauke96** [comment]
Found the problem: The handling of MultiPolygon geometries was not correct. This will be fixed in the upcoming 1.6.0 release.
