### ISSUE TITLE
Chat within project

### ISSUE THREAD

**Issue by hauke96** [hauke96/simple-task-manager#20]
Maybe a simple chat would be nice in a project. But there are some questions:

* Is that something important? Does anyone need such functionality?
* Per-project chat, per-task chat or both?
* How sophisticated/complex is this?
* Are there any helpful libraries?

There are also some things to consider:
* We need websockets for this in order to update the chat #19

**Comment by hauke96** [comment]
The result of this issue, as it is a "discussion"-issue, should not contain any implementation. However, during the research about a chat, new issues for project 1.1.0 should be created.

**Comment by qeef** [comment]
This comment is for inspiration and to answer *How sophisticated/complex is this?*.

I implemented a chat in [damn client](https://client.damn-project.org/). I use [wschat](https://sr.ht/~qeef/wschat/) for a server and a little bit of JavaScript [1](https://gitlab.com/damn-project/damn_client/-/blob/master/static/f.js#L8), [2](https://gitlab.com/damn-project/damn_client/-/blob/master/static/f.js#L276), [3](https://gitlab.com/damn-project/damn_client/-/blob/master/static/f.js#L641) in the client. Feel free to check it out.

**Comment by miurahr** [comment]
I've run small project during 'geoweek and weekend 2020' in Japan in Nov 2020.
The online event run on Discord chat/web conferencing service, and we don't need another chat among attendees.
Also local community run daily mapping event using slack in Japan.

Here, I'd like to put an idea 'chat-integration' feature.

- A feature that we can put chat invitation URL, QR-Code on project preference, or automatically join chat service when join the project.

- A feature that STM can push event notification onto web-hook, or chat bot. It requires a feature to put web-hook URL in project configuration, or capability to get an App OAUTH on several popular chat services. 

- Candidate for integration: slack, discord, telegram

**Comment by hauke96** [comment]
@miurahr I understand your point but I see that as an extension to a local chat within stm. Like a setting in the project creation where the creator can choose between a local chat and different integrations of external services.
