### ISSUE TITLE
Add "unassign"-button to all tasks for owners

### ISSUE THREAD

**Issue by hauke96** [hauke96/simple-task-manager#201]
An owner of a project currently has no option to unassign inactive users from a task. In other words: An inactive but assigned user stays assigned to that task forever.

**Current workaround:** The owner can remove (and re-add) the inactive user, causing all assignments of that user to be reset.

## Proposed feature

Add the "unassign"-button for the owner to all assigned tasks. This would allow the owner of a project to unassign inactive users from a task.

Feel free to add comment/feedback on this idea.

**Comment by govvin** [comment]
Thank you for considering this, @hauke96 .

Have you thought of adding multiple user assignment to tasks? This wouldn't necessitate the un-assignment (removal) of the first user, but the next user(s) can help complete a task, too -- and keeping the previously assigned user(s) acknowledges their contribution.

**Comment by hauke96** [comment]
That would be a another option of solving this problem, yes. But I don't know if it's a good idea to allow anyone to assign themselves to already assigned tasks. It probably depends on the people and size of the team, but that might lead to problems when two (or more) people are mistakenly working on the same task, because the second person e.g. didn't pay attention. But maybe this is just a theoretical problem and I'm overthinking it :smile: 

I personally haven't experienced a situation where any of this was necessary (un-assign button for the owner or multiple assigned people), so I cannot tell which solution is better.

**Comment by hauke96** [comment]
I added an unassign-button for project owners. They can now unassign any other user from a task. Feel free to checkout the change on https://stm-test.hauke-stieler.de/ (account on the OSM dev environment master.apis.dev.openstreetmap.org is needed).
