### ISSUE TITLE
Certain client actions cause double requests

### ISSUE THREAD

**Issue by andrewtwelch** [hauke96/simple-task-manager#210]
On a brand new install, when clicking buttons in the client, I'm seeing two requests going through, causing double ups on actions. I've noticed this so far with creating a new project (creates the project twice), importing a project (open file prompt shows twice when closed), and exporting a project (two identical files download). Dev Tools > Network shows duplicate identical requests for each action.

Tested in a normal browser window and incognito in Chrome 123.0.6312.88, and a normal browser window in Firefox 124.0.2. Also tested on another computer with Chrome 123.0.6312.86.

**Comment by andrewtwelch** [comment]
Seems like this is occurring with almost every action in the client after a bit more testing, anything that refreshes the page just fails the second request since the first one succeeds and the page reloads (i.e. opening a project, going back to the project list)

**Comment by hauke96** [comment]
Thanks for the bug report, I can reproduce the issue. However, some actions work as expected, e.g. saving progress points on a task. I'll look into this.

**Comment by hauke96** [comment]
This will be fixed in v1.6.0.
