### ISSUE TITLE
Error on saving new project

### ISSUE THREAD

**Issue by InsertUser** [hauke96/simple-task-manager#219]
I'm getting an error when trying to save a new project:

> Could not create project: runtime error: invalid memory address or nil pointer dereference

Created using the in browser tool, no import, GeoJson or other weirdness. 

Tested in Firefox and Chrome.

**Comment by hauke96** [comment]
Hi, thanks for the bug report. I just tried it and can't reproduce this issue, the backend logs unfortunately show no further information. Please provide the exact data (geometries and attributes) you create/enter when creating a project, feel free to add screenshots.

**Comment by InsertUser** [comment]
I don't know how to export the data for a project created in browser. I have five existing projects if that makes a difference. 

My steps to get the errors are fairly straightforward, but I have included them anyway. 

1. Click "Create project"
2. add title "test1"
3. click pencil outline tool and start creating outline (image 1)
4. close outline (image 2)
5. add a description
6. click save 
7. receive errors (image 3, 4)

In my original attempts I had used the subdivide tool to get the tasks down to 90m squares, but that doesn't seem to be necessary for me to get the error. I have tested with as few as four points on the outline. uBlock isn't reporting any domains blocked so I don't think that would be interfering.

Image 1:
![image 1](https://github.com/user-attachments/assets/f432dad7-d78f-4e31-84ce-5ff083135511)

Inage 2:
![image 2](https://github.com/user-attachments/assets/8249e480-a8c9-4edd-a9df-4c059c5edcca)

Image 3: 
![image 3](https://github.com/user-attachments/assets/813f7251-11cd-441b-80c8-b1962195b178)

Image 4: 
![image](https://github.com/user-attachments/assets/f11c0833-ed73-42c3-a4d6-441f0afa7162)

**Comment by hauke96** [comment]
Thanks for the details. I'm not able to reproduce the issue with a new project, but I added myself to your project and can confirm the issue there. There seems to be something wrong with the project. I don't know what, but I'll look into it.

**Comment by hauke96** [comment]
Unfortunately, I was not able to get to the bottom of this error. Everything worked on my machine (with the same database). I restarted the server and now, the issue is gone for me. Please check, whether the problem is gone for you, too.

**Comment by InsertUser** [comment]
Thank you. 

I'm able to save on my old projects and managed to create a new one. 

I'll mark this as closed as it's working now. I hope it's just a one off glitch.
