### ISSUE TITLE
This is just "Hi!" issue

### ISSUE THREAD

**Issue by qeef** [hauke96/simple-task-manager#43]
Hi! :)

That's what I wanted to say. And yes, I am going to benchmark your project against [the damn project](https://www.damn-project.org/) and against [HOT TM](https://tasks.hotosm.org/), when I have a little bit of time. I am really curious about the performance.

Anyway, I found that you have some issues (like #38) about GeoJSON opened. Feel free to check out my solution in [damn server](https://gitlab.com/damn-project/damn_server). Hope it will be helpful.

I was thinking about chat (#20) for the [damn client](https://gitlab.com/damn-project/damn_client/), too, and I think that online IRC client may do a great job here.

Feel free to close the issue. Just wanted to greet you a say that you are working on a great project!

**Comment by hauke96** [comment]
Hi :)

sure, feel free to play around. However, keep in mind, that this is currently under heavy development and I do currently deploy this when ever I want and sometimes I break things :D I also haven't announced anything yet (e.g. via OSM mailing list), so currently this is something like in the alpha development stage.

Regarding #38, I took a look at your database structure and you don't store a full GeoJSON string but rather the FeatureCollection part of it in the database (`featurecollection` column in the `current_areas` table)?

Regarding chat, I haven't looked into it yet. An IRC Server of course would work but then there's an additional server to manage and to run. I don't know if that's easy to setup, use and maintain. But yes, I also thought about something like that. A manual solution (meaning building an own chat solution) would also be good when e.g. exporting a project including the chat. Maybe that's also possible with IRC, I don't know. You see I really haven't thought about this yet :D

Thanks, I'm glad that you like it :) But I have one question left: How have you discovered this project? I haven't yet told a lot of people.

**Comment by qeef** [comment]
Regarding #38 -- in `area`, the whole GeoJSON is stored as JSON. During area creation, the features of GeoJSON are processed and geometry created for each `square`. Yes, it expects the GeoJSON of FeatureCollection as input when creating area. The reason is the compatibility with MapSwipe Analytics and geojson.io.

And, well, @jmacura starred your repo, so...

**Comment by hauke96** [comment]
Thanks for the explanation. I also think that GeoJSON is a good choice for a string based area storage.

**Comment by jmacura** [comment]
And there comes another "hi" from me as well..
If you are curious how I have discovered your repo, I am not even sure, but I believe it was some secret GitHub logic, which made it pop-up in my GitHub main page... 😕 
But anyway, I think this project is interesting, so it certainly deserves a star! I can only be glad that other people working on similar projects (@qeef  ;-) ) spotted it.
