### ISSUE TITLE
Preview when dividing polygons

### ISSUE THREAD

**Issue by seb-1204** [hauke96/simple-task-manager#97]
A suggestion to improve the polygon creation workflow.
Instead of loosing the polygon after the shapes have been created I suggest the following.

1. Draw polygon
2. overlay the shapes at the current selected size
3. have two options, change shape parameters or accept
4. delete polygon.

I suggest that as I am assuming making the polygon editable etc. is a lot of work while this might be easier to implement.

**Comment by hauke96** [comment]
Thanks for the suggestion but do I understand it correctly?

* there should be a preview when dividing a polygon into e.g. hexagons
* the user then can decide whether to accept the preview or to abort dividing the polygon and get the original back

**Comment by seb-1204** [comment]
Yes, that is correct. I was suggesting some form of preview. On the two test projects I've done I had several attempts to get a good grid size. This would make it easier as the polygon will not be 'lost'.

**Comment by hauke96** [comment]
Sound like a nice feature, thanks for the suggestion. I already added this issue to the 1.2.0 project, so this will probably be part of the 1.2.0 release.
